### ISSUE TITLE
Path array in patters

### ISSUE THREAD

**Issue by josecelano** [M6Web/FirewallBundle#10]
It would be great to do this:

```
    patterns: 
        frontend:
            config: frontend
            path: /
        backend:
            config: backend
            path: 
                - /admin
                - /superadmin
                ...
```

instead of this:

```
    patterns: 
        frontend:
            config: frontend
            path: /
        backend_admin:
            config: backend
            path: /admin
        backend_superadmin:
            config: backend
            path: /superadmin
```

Great bundle!!! Thanks.
